### ISSUE TITLE
Numbering Chapter Titles

### ISSUE THREAD

**Issue by ggarcia0596** [gettypubs/restoration-ancient-bronzes#6]
While manually numbering chapter titles in their individual markdown files, `#.` cannot be used a stylization, but `#)` can. The former doesn't properly show up on the chapter's page in the heading. Alternatively if there is another method of having chapters be numbered without it infringing upon the title itself may also be useful.

**Comment by geealbers** [comment]
Yes, good catch. What's going on here is that the title is being rendered as Markdown, and in Markdown `#.` indicates the start of a numbered list. And because of the overly-aggressive renderer built into Quire, the Markdown list is also being renumbered to always start at "1." even if in the code you had "4." or another number.

The solution to this is to use Quire's built-in `number` parameter, which adds the chapter number to the title after the rendering. The added benefit to this method is that it's more semantic to keep the chapter title, separate from the chapter number (such as when used for citations). The markup looks like this:

```yaml
number: 4
title: The Restoration History of the Bronze Apollo and Diana from Pompeii
```

**Comment by ggarcia0596** [comment]
Thank you! All the numbers have been switched.
